version: '3'
services:

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn django-vote-15th.wsgi:application --bind 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: django-vote-15th.settings.prod
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8000
    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - type: bind
        source: /home/app/web/certbot/conf/live
        target: /etc/nginx/ssl
      - /home/app/web/certbot/data:/var/www/certbot
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  static:
  media: